# Generated by Django 5.0.1 on 2024-04-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='pho',
            new_name='pno',
        ),
        migrations.AlterField(
            model_name='emp',
            name='email',
            field=models.CharField(max_length=300),
        ),
    ]
